version: "3"

services:
  formato120_mysql:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: ${MSQL_CONTAINER_NAME}

  wordpress:
    depends_on:
      - ${MSQL_CONTAINER_NAME}
    image: wordpress:latest
    expose:
      - 80
      - 443
    restart: always
    environment:
      VIRTUAL_HOST: formato120.it,www.formato120.it
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      WORDPRESS_DB_HOST: ${MSQL_CONTAINER_NAME}:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    container_name: formato120_wp
    volumes:
      - ./public/wp-content:/var/www/html/wp-content
      - ./public/.htaccess:/var/www/html/.htaccess

  phpmyadmin:
    depends_on:
      - ${MSQL_CONTAINER_NAME}
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      VIRTUAL_HOST: ${PMA_URL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      PMA_HOST: ${MSQL_CONTAINER_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  default:
    external:
            name: nginx-proxy
